name: Continuous Delivery
on:
  pull_request:
    types:
      - closed
    branches: 
      - master  

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions: 
        contents: write

    steps: 
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Process Pull Request
        id: process-pr
        run: |
          LABELS=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")
          echo "::debug::Labels: $LABELS"

          if echo "$LABELS" | grep -q 'major'; then
            RELEASE_TYPE_TAG="major"
          elif echo "$LABELS" | grep -q 'minor'; then
            RELEASE_TYPE_TAG="minor"
          elif echo "$LABELS" | grep -q 'patch'; then
            RELEASE_TYPE_TAG="patch"
          else
            echo "::error::No tag found matching a release type."
            exit 1
          fi

          echo "Release tag: $RELEASE_TYPE_TAG"
          echo "release_type=$RELEASE_TYPE_TAG" >> $GITHUB_OUTPUT

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Create or Update release type tag
        run: |
          git tag -fa ${{ steps.process-pr.outputs.release_type }} -m "${{ steps.process-pr.outputs.release_type }}"
          git push origin -f ${{ steps.process-pr.outputs.release_type }}
